#!/usr/bin/env python

import sys
import subprocess

try:
    encoding = sys.argv[1]
    filename = sys.argv[2]
except IndexError:
    print >>sys.stderr, "Usage: ./convert-utf8 <encoding> <filename>"
    sys.exit(1)

subprocess.check_call(['iconv', '-f', encoding, '-t', 'utf-8', filename])
